# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.ImageField(upload_to='')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryapp.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='deliveryapp.Order')),
            ],
        ),
    ]
