# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0005_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.IntegerField(),
        ),
    ]
