# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0006_auto_20180504_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryapp.Driver'),
        ),
    ]
