# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0007_auto_20180505_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
